version: '3'

services:
  mongodb:
    image: mongo:4.4
    platform: linux/arm64/v8
    container_name: NodeJS_FS_MongoDB
    ports:
      - "27017:27017"
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: admin
    #   MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data: